/*
---
description: Kiosk Scroll built on the MooTools Framework

license: MIT-style

authors:
- Thomas Kunambi
- kunambi

requires:
- core/1.2.5: [Class, Element.Event, Element.Style, Fx.Tween]
*/

var KioskScroll=new Class({Implements:Options,options:{width:null,height:null,duration:5,transition:200,clickframe:false,showanchors:true,useanchors:true,autostart:true,periodical:true},initialize:function(a){this.setOptions(a);try{this.element=document.id(this.options.element)||this.options.element;if(this.element===null){throw ("DOM object not found")}}catch(b){alert(b);return}this.timer=null;this.curr=0;if(!isNaN(this.options.width)){this.element.setStyle("width",this.options.width)}if(!isNaN(this.options.height)){this.element.setStyle("height",this.options.height)}if(this.options.showanchors){this.navigator=new Element("ul.kiosk-nav").inject(this.element);this.element.getElements("ul:first-child > li").each(function(d,c){if(c>0){d.setStyles({"opacity":0,"display":"none"})}if(this.options.clickframe){d.setStyle("cursor","pointer");d.addEvent("click",function(f){f.preventDefault();clearTimeout(this.timer);this.scrollToPane(c+1)}.bind(this))}if(this.options.useanchors){new Element("li",{"class":!c?"active":""}).adopt(new Element("a",{html:c+1,href:"javascript:;"}).addEvent("click",function(f){f.preventDefault();clearTimeout(this.timer);this.scrollToPane(c)}.bind(this))).inject(this.navigator)}else{new Element("li",{html:c+1,"class":!c?"active":""}).inject(this.navigator)}}.bind(this))}if(this.options.autostart){this.start()}},start:function(){if(this.options.periodical){this.isPlaying=true;this.timer=this.scrollToPane.delay(this.options.duration*1000,this,[undefined])}else{this.scrollToPane()}},stop:function(){if(this.isPlaying){clearTimeout(this.timer);this.isPlaying=false}},scrollToPane:function(a){if(!!a||a===0){this.next=(a<this.element.getElements("ul:first-child > li").length)?a:0}else{this.next=(this.curr<this.element.getElements("ul:first-child > li").length-1)?this.curr+1:0}this._fadeOut(true);if(this.isPlaying){this.timer=this.scrollToPane.delay(this.options.duration*1000,this,[undefined])}},_fadeOut:function(a){var b=this.element.getElements("ul:first-child > li")[this.curr];new Fx.Tween(b,{duration:this.options.transition,transition:Fx.Transitions.Sine.easeInOut,onComplete:function(){b.setStyle("display","none");if(this.options.showanchors){this.navigator.getElements("li.active").removeClass("active")}if(a){this._fadeIn(this.next)}}.bind(this)}).start("opacity",0)}.protect(),_fadeIn:function(a){this.curr=a;var b=this.element.getElements("ul:first-child > li")[a];b.setStyle("display","block");if(this.options.showanchors){this.navigator.getElements("li")[a].addClass("active")}new Fx.Tween(b,{duration:this.options.transition,transition:Fx.Transitions.Sine.easeInOut}).start("opacity",1)}});